name: Daily Horoscope

on:
  schedule:
    - cron: '0 5 * * *' # 08:00 по Москве (UTC+3 → UTC 5:00)
  workflow_dispatch:

jobs:
  post_horoscope:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pyTelegramBotAPI schedule

      - name: Run bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        run: python bot.py
